"""empty message

Revision ID: 354e9c512788
Revises: ea175c24dcf2
Create Date: 2019-11-08 14:23:56.098488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354e9c512788'
down_revision = 'ea175c24dcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
